# Generated by Django 3.0 on 2019-12-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_id', models.CharField(max_length=4, unique=True)),
                ('clg_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=5, unique=True)),
                ('stream_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('reg_no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Registration Number')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contect_no', models.IntegerField(verbose_name='Contect No')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('is_participant', models.BooleanField(default=False, verbose_name='Participant')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Event Committee')),
                ('clg', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.College', verbose_name='Collage')),
                ('stream', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.Stream', verbose_name='Stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
