# Generated by Django 2.2.7 on 2019-11-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('contect_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_participant', models.BooleanField(default=False)),
                ('is_event_commitee', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('clg_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Collages')),
                ('stream', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
