# Generated by Django 3.0 on 2019-12-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Committee',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('committee_id', models.CharField(max_length=20, unique=True)),
                ('yearOfStudy', models.IntegerField()),
                ('is_vol', models.BooleanField(default=False)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('is_event_head', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('in_sponsorship', models.BooleanField(default=False)),
                ('in_publicity', models.BooleanField(default=False)),
                ('in_criative', models.BooleanField(default=False)),
                ('in_technical', models.BooleanField(default=False)),
                ('in_volunteering', models.BooleanField(default=False)),
                ('in_logistics', models.BooleanField(default=False)),
                ('in_graphics', models.BooleanField(default=False)),
                ('in_eventManagement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManager.Event_Committee')),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManager.Event_Committee')),
                ('payment_hold', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManager.Event_Committee')),
                ('payment_hold', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
