# Generated by Django 3.0 on 2019-12-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_admin_coordinator_event_committee_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='reg_no',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
