# Generated by Django 2.2.7 on 2019-11-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_admin_coordinator_event_commitee_event_head_participant_publicity_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_commitee',
            old_name='year',
            new_name='yearOfStudy',
        ),
        migrations.AlterField(
            model_name='user',
            name='clg_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Collages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Stream'),
        ),
    ]
