# Generated by Django 3.0 on 2019-12-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_auto_20191214_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('reg_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManager.Event_Committee')),
                ('payment_hold', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
