# Generated by Django 3.0 on 2019-12-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='clg_id',
            field=models.CharField(max_length=4, unique=True, verbose_name='Collage Id'),
        ),
        migrations.AlterField(
            model_name='college',
            name='clg_name',
            field=models.CharField(max_length=100, verbose_name='Collage Name'),
        ),
    ]
