# Generated by Django 2.2.7 on 2019-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_auto_20191119_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_event_commitee',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Event Committee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clg_id',
            field=models.ForeignKey(default='O', on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Collages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(default='CSE', on_delete=django.db.models.deletion.SET_DEFAULT, to='UserManager.Stream'),
        ),
    ]
