# Generated by Django 2.2.7 on 2019-11-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0005_auto_20191121_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clg_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.Collages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.Stream'),
        ),
    ]
