# Generated by Django 2.2.7 on 2019-11-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0007_auto_20191121_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='is_admin',
        ),
    ]
