# Generated by Django 2.2.7 on 2019-11-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0009_auto_20191121_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicity_Volunteer',
            new_name='Volunteer',
        ),
    ]
