# Generated by Django 2.2.7 on 2019-11-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0010_auto_20191124_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_commitee',
            old_name='commitee_id',
            new_name='committee_id',
        ),
    ]
