# Generated by Django 2.2.7 on 2019-11-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0011_auto_20191124_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='payment_hold',
            field=models.IntegerField(default=0),
        ),
    ]
