# Generated by Django 2.2.7 on 2019-11-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0012_auto_20191124_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='event_commitee',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='event_head',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='reg_no',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Event_Commitee',
        ),
        migrations.DeleteModel(
            name='Event_Head',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
