# Generated by Django 2.2.7 on 2019-11-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0015_admin_coordinator_event_head_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Registration Number'),
        ),
    ]
