# Generated by Django 2.2.7 on 2019-11-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0016_auto_20191125_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
