# Generated by Django 2.2.7 on 2019-11-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0026_remove_winner_event_head_id'),
        ('UserManager', '0017_delete_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Head',
        ),
    ]
