# Generated by Django 2.2.7 on 2019-11-27 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventWebSite', '0026_remove_winner_event_head_id'),
        ('UserManager', '0018_delete_event_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventWebSite.Event')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Event_Committee')),
            ],
        ),
    ]
