# Generated by Django 3.0 on 2019-12-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0004_volunteer'),
        ('EventWebSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventWebSite.Event')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Event_Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')])),
                ('winning_certificate_issue', models.BooleanField(default=False)),
                ('winning_certi_otp', models.IntegerField()),
                ('event_head_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventHead.Event_Head')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventWebSite.Event')),
                ('winner_reg_no', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EventWebSite.Participation')),
            ],
        ),
    ]
