# Generated by Django 3.0 on 2019-12-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventHead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='event_head_id',
            new_name='event_head',
        ),
        migrations.RenameField(
            model_name='winner',
            old_name='winner_reg_no',
            new_name='winner',
        ),
    ]
