# Generated by Django 2.2.7 on 2019-11-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventHead', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Head',
        ),
    ]
