# Generated by Django 3.0 on 2019-12-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vol_to_admin_pay',
            old_name='a_id',
            new_name='reg_no',
        ),
    ]
