# Generated by Django 3.0 on 2019-12-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='event_id',
            new_name='event',
        ),
    ]
