# Generated by Django 2.2.7 on 2019-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_containt',
        ),
        migrations.AddField(
            model_name='news',
            name='news_content',
            field=models.TextField(default='hiiiii', verbose_name='News Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='for_whome',
            field=models.CharField(choices=[('Participants', 'Participants'), ('Volunteer', 'Volunteer')], max_length=50, verbose_name='News Viewers'),
        ),
        migrations.AlterField(
            model_name='news',
            name='hyperlink',
            field=models.CharField(max_length=50, verbose_name='hyperlink'),
        ),
    ]
