# Generated by Django 2.2.7 on 2019-11-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0002_auto_20191121_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.CharField(max_length=1000, verbose_name='News Content'),
        ),
    ]
