# Generated by Django 2.2.7 on 2019-11-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0003_auto_20191122_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
        migrations.DeleteModel(
            name='Parent_event',
        ),
    ]
