# Generated by Django 2.2.7 on 2019-11-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0004_auto_20191123_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Evnet_Detail',
            new_name='event_detail',
        ),
    ]
