# Generated by Django 2.2.7 on 2019-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0005_auto_20191123_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(blank=True, null=True, upload_to='event_logo/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Scrapped', 'Scrapped'), ('Delete', 'Delete'), ('Full', 'Full')], max_length=30),
        ),
    ]
