# Generated by Django 2.2.7 on 2019-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0006_auto_20191123_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(null=True, upload_to='event_logo/'),
        ),
    ]
