# Generated by Django 2.2.7 on 2019-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0007_auto_20191123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(null=True, upload_to='uploaded_media/event_logo/'),
        ),
    ]
