# Generated by Django 2.2.7 on 2019-11-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0009_auto_20191124_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='filled_by',
        ),
    ]
