# Generated by Django 2.2.7 on 2019-11-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0010_auto_20191124_0433'),
        ('EventWebSite', '0010_remove_registers_filled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='filled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.Volunteer'),
        ),
    ]
