# Generated by Django 2.2.7 on 2019-11-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0011_registers_filled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='sponsers',
            name='done_by',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='event_head_id',
        ),
        migrations.DeleteModel(
            name='vol_to_admin_pay',
        ),
    ]
