# Generated by Django 2.2.7 on 2019-11-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0013_auto_20191124_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='event_attendance_qr',
        ),
        migrations.RemoveField(
            model_name='registers',
            name='conformed',
        ),
        migrations.AlterField(
            model_name='registers',
            name='filled_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManager.Volunteer'),
        ),
    ]
