# Generated by Django 2.2.7 on 2019-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0014_auto_20191124_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
