# Generated by Django 2.2.7 on 2019-11-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0015_event_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='paid_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registers',
            name='remark',
            field=models.TextField(default=None),
        ),
    ]
