# Generated by Django 2.2.7 on 2019-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0016_auto_20191125_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='remark',
            field=models.TextField(default=None, null=True),
        ),
    ]
