# Generated by Django 2.2.7 on 2019-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0017_auto_20191125_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='Event Date & Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_detail',
            field=models.TextField(verbose_name='Event Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Event Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(null=True, upload_to='event_logo/', verbose_name='Event Logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Scrapped', 'Scrapped'), ('Delete', 'Delete'), ('Full', 'Full')], max_length=30, verbose_name='Event Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fees',
            field=models.IntegerField(verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=50, verbose_name='Venue'),
        ),
    ]
