# Generated by Django 2.2.7 on 2019-11-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0018_auto_20191125_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='amount',
        ),
    ]
