# Generated by Django 2.2.7 on 2019-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0019_remove_participation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='reg_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid'), ('Comform', 'Conform'), ('Attended', 'Attended'), ('Certificate Issued', 'Certificate Issued'), ('Attended Winner', 'Attended Winner'), ('Scrapped', 'Scrapped'), ('Delete', 'Delete')], max_length=50),
        ),
    ]
