# Generated by Django 2.2.7 on 2019-11-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0020_auto_20191127_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date & Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=50, null=True, verbose_name='Venue'),
        ),
    ]
