# Generated by Django 2.2.7 on 2019-11-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0022_participation_attendance_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='winner_reg_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='EventWebSite.Participation'),
        ),
    ]
