# Generated by Django 2.2.7 on 2019-11-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0023_auto_20191127_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='certi_otp',
            new_name='winning_certi_otp',
        ),
    ]
