# Generated by Django 2.2.7 on 2019-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0024_auto_20191127_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='reg_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid'), ('Comform', 'Conform'), ('Attended', 'Attended'), ('Attended Winner', 'Attended Winner'), ('Certificate Issued', 'Certificate Issued'), ('Winner Certificate Issued', 'Winner Certificate Issued'), ('Scrapped', 'Scrapped'), ('Delete', 'Delete')], max_length=50),
        ),
    ]
