# Generated by Django 2.2.7 on 2019-11-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0025_auto_20191127_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='event_head_id',
        ),
    ]
