# Generated by Django 2.2.7 on 2019-11-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventWebSite', '0027_event_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='event_head_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventWebSite.Event_Head'),
        ),
    ]
